### ISSUE TITLE
Arcball breaks if we come to close to 0,0,0

### ISSUE THREAD

**Issue by vorg** [variablestudio/pex-cam#1]

**Comment by automat** [comment]
Actually thats whats going on:

**Comment by automat** [comment]
Actually this is happening:

```
Mat4.lookAt([0.0000001,0.0000001,0.0000001],[0,0,0],[0,1,0]);

//returns
// [ 1, 0, 0, 0, 
//   0, 1, 0, 0, 
//   0, 0, 1, 0, 
//   0, 0, 0, 1 ]
```

**Comment by vorg** [comment]
Right, my old code didn't that check for `Math.abs(eyex - targetx) < 0.000001`. Also because we have inertia when we scroll at some point Arcball just 'snaps' to 0,0,0. 

I would propose that we change [Arcball.js#L85](https://github.com/variablestudio/pex-cam/blob/master/Arcball.js#L85):

`this._distanceMin    = Number.MIN_VALUE;` to `2 * EPSILON`
